[theme]
name = Default

wallpaper         = hsl(220, 15%, 8%)

background-top    = hsl(220, 14%, 18%)
background        = hsl(220, 14%, 13%)
background-bottom = hsl(220, 14%, 10%)

border            = hsl(220, 14%, 22%)

text              = hsl(0, 0%, 100%)
text-muted        = hsl(0, 0%, 50%)

primary           = hsl(220, 13%, 22%)
primary-muted     = hsl(220, 13%, 15%)

secondary         = hsl(220, 13%, 30%)
secondary-muted   = hsl(220, 13%, 15%)

enabled           = hsl(130, 100%, 37%)
disabled          = hsl(0, 100%, 37%)

hud-elem-background = hsla(220, 15%, 8%, 0.70)
hud-elem-border = hsla(220, 10%, 65%, 0.90)
hud-elem-text = hsl(0, 0%, 100%)
hud-elem-accent = hsl(195, 100%, 58%)
hud-elem-tick-major = hsl(0, 0%, 92%)
hud-elem-tick-minor = hsla(0, 0%, 80%, 0.75)