[theme]
name = Default

wallpaper         = hsl(220, 13%, 5%)

background-top    = hsl(0, 0%, 24%)
background        = hsl(0, 0%, 19%)
background-bottom = hsl(0, 0%, 15%)

border            = hsl(220, 13%, 20%)

text              = hsl(0, 0%, 100%)
text-muted        = hsl(0, 0%, 70%)

primary           = hsl(220, 13%, 25%)
primary-muted     = hsl(220, 13%, 15%)

secondary         = hsl(220, 13%, 30%)
secondary-muted   = hsl(220, 13%, 15%)
